sudo: false
language: ruby
rvm:
  - 2.1.8
cache: bundler
branches:
  only:
    - master
env:
  global:
    - RACK_ENV=integration
install:
# FIX: cannot get the following to succeed on travis with sudo: required
# - sudo apt-get update -qq && apt-get install git-core subversion -y
  - rvm gemset use global
  - gem install chef -v 11.6.2 --no-rdoc --no-ri
  - bundle install
before_script:
# some setup for git to avoid prompting that breaks tests
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "[user]\n  name = Your Email\n  email = your_email@example.com\n\n[core]\n  excludesfile = ~/.gitignore\n\n" > ~/.gitconfig

script:
# set DISPLAY= to defeat prompts for password on travis where DISPLAY is somehow not empty by default.
# note that you can set verbose=true to display the full git commands, etc.
  - DISPLAY= rake spec
