sudo: required
language: ruby
rvm:
  - 2.1.8
cache: bundler
branches:
  only:
    - master
env:
  global:
    - RACK_ENV=integration
install:
# - sudo apt-get update -qq && apt-get install git-core subversion -y
  - rvm gemset use global
  - gem install chef -v 11.6.2 --no-rdoc --no-ri
  - bundle install
  - eval "$(ssh-agent -s)"  # start the ssh agent
script:
  - rake spec
