#--  -*-ruby-*-
# Copyright: Copyright (c) 2010 RightScale, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# 'Software'), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#++

require 'rubygems'
require 'rake'
require 'spec/rake/spectask'
require 'rake/rdoctask'
require 'rake/gempackagetask'
require 'rake/clean'

task :default => 'gem'

gemtask = Rake::GemPackageTask.new(Gem::Specification.load("right_scraper_all.gemspec")) do |package|
  package.package_dir = ENV['PACKAGE_DIR'] || 'pkg'
  package.need_zip = true
  package.need_tar = true
end

directory gemtask.package_dir

file "right_scraper_all.gemspec" => :populate_staging
directory "lib"

CLEAN.include('lib')
CLEAN.include(gemtask.package_dir)

task "lib/right_scraper_all.rb" => ["lib", "../right_scraper/lib/right_scraper.rb"] do
  # need to translate absolute gem requires to relative requires, so I use sed.
  sh %Q{sed "s/require '\\([a-z0-9_]*\\)'/\
require File.expand_path(File.join(File.dirname(__FILE__), '\\1'))/"\
 < '../right_scraper/lib/right_scraper.rb' > 'lib/right_scraper_all.rb'}
end

desc "Populate staging directory"
task :populate_staging => ["lib/right_scraper_all.rb"] do
  intermediate_dir = File.join(File.dirname(__FILE__), 'lib')
  when_writing("Copying right_scraper gems to lib") do
    Dir.glob('../right_scraper_*') do |file|
      next unless File.directory?(file)
      next if file == "../right_scraper_all"
      verbose(true) do
        cp_r(Dir.glob("#{file}/lib/*"), intermediate_dir)
      end
    end
  end
end
